package com.example.cineverse.presentation.designSystem.new_theme.light

import androidx.compose.ui.graphics.Color

// Generated from Figma color variables

val BackgroundScreen = Color(0xFFF7F7F7)
val ShadePrimary = Color(0xFF313131)
val BackgroundCard = Color(0xFFFFFFFF)
val BrandPrimary = Color(0xFF536DFE)
val ButtonPrimary = Color(0xFF536DFE)
val ButtonSecondary = Color(0xFFF1F3FF)
val BrandSecondary = Color(0xFFBEC8FF)
val BrandTertiary = Color(0xFFF1F3FF)
val BackgroundBottomSheet = Color(0xFFFFFFFF)
val BackgroundBottomSheetCard = Color(0xFFF6F6F6)
val ButtonDisabled = Color(0xFFE5E5E5)
val ButtonOnPrimary = Color(0xFFFFFFFF)
val ButtonOnSecondary = Color(0xFF717171)
val ButtonOnTertiary = Color(0xFF536DFE)
val ButtonOnDisabled = Color(0xFFA5A5A5)
val StrokePrimary = Color(0xFFECECEC)
val AdditionalPrimaryRed = Color(0xFFEF4444)
val AdditionalSecondaryRed = Color(0xFFFBEEEE)
val AdditionalSecondaryGreeen = Color(0xFFEEF5EF)
val AdditionalSecondaryYellow = Color(0xFFFFFAEB)
val AdditionalSecondaryShimmer = Color(0x14121212)
val AdditionalPrimaryGreen = Color(0xFF22C55E)
val AdditionalPrimaryYellow = Color(0xFFFACC15)
val OverlayPrimary = Color(0x99FFFFFF)
val OverlaySeconadry = Color(0x3DFFFFFF)
val AdditionalTEMP = Color(0x00FFFFFF)
val ShadeSecondary = Color(0xFF717171)
val ShadeTertiary = Color(0xFFA5A5A5)
val ShadeQuaternary = Color(0xFFECECEC)
val ShadeQuinary = Color(0xFFF6F6F6)
